Using SQL to clean and transform data (ELT: Extract, Load, Transform)
To use DuckDB inside VS Code/ Jupyter Notebook

In [29]:
import duckdb
# create a connection to duckdb
con = duckdb.connect()
print("DuckDB SQL Engine Ready!")

DuckDB SQL Engine Ready!

In [30]:
# read raw data
view_query = """
    SELECT * FROM read_csv_auto('../data/SGJobData.csv')
    LIMIT 4;
    """
# show table
con.sql(view_query).df()

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
0,"[{""id"":13,""category"":""Environment / Health""},{...",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,...,None,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0
1,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,...,None,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0
2,"[{""id"":33,""category"":""Repair and Maintenance""}]",Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,...,None,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0
3,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,...,None,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0

In [31]:
# try to load raw data from hard drive to temporary table in RAM to work on
setup_query = """
    CREATE OR REPLACE TABLE raw_jobs AS
    SELECT * FROM read_csv_auto('../data/SGJobData.csv');
"""
con.sql(setup_query)

In [33]:
# view raw_Job table
con.sql("SELECT * FROM raw_jobs LIMIT 4;").df()

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
0,"[{""id"":13,""category"":""Environment / Health""},{...",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,...,None,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0
1,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,...,None,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0
2,"[{""id"":33,""category"":""Repair and Maintenance""}]",Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,...,None,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0
3,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,...,None,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0

In [34]:
# describe table
con.sql("DESCRIBE SELECT * FROM raw_Jobs;")

┌────────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│            column_name             │ column_type │  null   │   key   │ default │  extra  │
│              varchar               │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ categories                         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ employmentTypes                    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_expiryDate                │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_isPostedOnBehalf          │ BOOLEAN     │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_jobPostId                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_newPostingDate            │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_originalPostingDate       │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_repostCount               │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_totalNumberJobApplication │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ metadata_totalNumberOfView         │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ minimumYearsExperience             │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ numberOfVacancies                  │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ occupationId                       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ positionLevels                     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ postedCompany_name                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ salary_maximum                     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ salary_minimum                     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ salary_type                        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ status_id                          │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ status_jobStatus                   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ title                              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ average_salary                     │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
├────────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┤
│ 22 rows                                                                        6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────┘

In [37]:
con.sql("DESCRIBE raw_Jobs;").df()

                           column_name column_type null   key default extra
0                           categories     VARCHAR  YES  None    None  None
1                      employmentTypes     VARCHAR  YES  None    None  None
2                  metadata_expiryDate        DATE  YES  None    None  None
3            metadata_isPostedOnBehalf     BOOLEAN  YES  None    None  None
4                   metadata_jobPostId     VARCHAR  YES  None    None  None
5              metadata_newPostingDate        DATE  YES  None    None  None
6         metadata_originalPostingDate        DATE  YES  None    None  None
7                 metadata_repostCount      BIGINT  YES  None    None  None
8   metadata_totalNumberJobApplication      BIGINT  YES  None    None  None
9           metadata_totalNumberOfView      BIGINT  YES  None    None  None
10              minimumYearsExperience      BIGINT  YES  None    None  None
11                   numberOfVacancies      BIGINT  YES  None    None  None
12                        occupationId     VARCHAR  YES  None    None  None
13                      positionLevels     VARCHAR  YES  None    None  None
14                  postedCompany_name     VARCHAR  YES  None    None  None
15                      salary_maximum      BIGINT  YES  None    None  None
16                      salary_minimum      BIGINT  YES  None    None  None
17                         salary_type     VARCHAR  YES  None    None  None
18                           status_id      BIGINT  YES  None    None  None
19                    status_jobStatus     VARCHAR  YES  None    None  None
20                               title     VARCHAR  YES  None    None  None
21                      average_salary      DOUBLE  YES  None    None  None

In [ ]:
# shows Data Types, Min, Max, Unique Counts, and Null percentages for ALL columns
con.sql("SUMMARIZE raw_jobs;").df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,categories,VARCHAR,"[{""id"":1,""category"":""Accounting / Auditing / T...","[{""id"":9,""category"":""Design""}]",24514,None,None,None,None,None,1048585,0.38
1,employmentTypes,VARCHAR,Contract,Temporary,6,None,None,None,None,None,1048585,0.38
2,metadata_expiryDate,DATE,2023-04-04,2024-12-12,447,None,None,2023-08-19,2023-11-25,2024-03-15,1048585,0.38
3,metadata_isPostedOnBehalf,BOOLEAN,false,true,2,None,None,None,None,None,1048585,0.00
4,metadata_jobPostId,VARCHAR,ATS-2023-0275189,RANDOM_JOB_20251115011349636339_9,941119,None,None,None,None,None,1048585,0.38
5,metadata_newPostingDate,DATE,2023-02-24,2024-05-29,443,None,None,2023-07-25,2023-10-29,2024-02-20,1048585,0.38
6,metadata_originalPostingDate,DATE,2022-10-03,2024-05-29,769,None,None,2023-07-23,2023-10-29,2024-02-20,1048585,0.38
7,metadata_repostCount,BIGINT,0,2,3,0.05472326993043006,0.2822675006892892,0,0,0,1048585,0.00
8,metadata_totalNumberJobApplication,BIGINT,0,1342,472,2.13657071195945,10.62612311939964,0,0,1,1048585,0.00
9,metadata_totalNumberOfView,BIGINT,0,8190,1916,26.74535969902297,82.62001425060542,1,4,17,1048585,0.00
10,minimumYearsExperience,BIGINT,0,88,49,2.779573425139593,2.5370492300360237,1,2,4,1048585,0.00
11,numberOfVacancies,BIGINT,0,999,108,2.6800431057091223,11.243005255704043,1,1,2,1048585,0.00
12,occupationId,VARCHAR,None,None,0,None,None,None,None,None,1048585,100.00
13,positionLevels,VARCHAR,Executive,Senior Management,9,None,None,None,None,None,1048585,0.38
14,postedCompany_name,VARCHAR,"""K"" LINE LOGISTICS (SINGAPORE) PTE. LTD.",Zu-Lin Temple Association,52640,None,None,None,None,None,1048585,0.38
15,salary_maximum,BIGINT,0,25330000,3134,5723.577999876024,50183.870161534425,3283,4500,6477,1048585,0.00
16,salary_minimum,BIGINT,0,350000,2003,3815.312212171641,3172.181716465717,2500,3000,4451,1048585,0.00
17,salary_type,VARCHAR,Monthly,Monthly,1,None,None,None,None,None,1048585,0.38
18,status_id,BIGINT,0,0,1,0.0,0.0,0,0,0,1048585,0.00
19,status_jobStatus,VARCHAR,Closed,Re-open,3,None,None,None,None,None,1048585,0.38
20,title,VARCHAR,\t SAP Specialist (Hana OR FICO/ Logistics MNC...,🫳Parcel Sorter📦@$11/Hr,378749,None,None,None,None,None,1048585,0.38
21,average_salary,DOUBLE,0.0,12666400.0,5042,4769.4451060238325,25478.09003076534,2896.2118353603664,3803.5825095412292,5470.810244409964,1048585,0.00

In [58]:
# futher check on salary_type
unique_query = """
    SELECT DISTINCT salary_type, count(*) as count
    FROM raw_jobs
    GROUP BY salary_type;
"""

con.sql(unique_query).df()

  salary_type    count
0     Monthly  1044597
1        None     3988

In [ ]:
# show value count for all column (same as df.info or value_count in pandas)
# Step 1: Tell DuckDB to get a list of all column names in the 'raw_jobs' table
columns_df = con.sql("SELECT column_name FROM information_schema.columns WHERE table_name = 'raw_jobs'").df()

# Step 2: Extract the column names as a Python list
col_list = columns_df['column_name'].tolist()

# Step 3: Loop through each column and run a value_counts SQL query!
for col in col_list:
    print(f"\n--- Top 5 Value Counts for: {col} ---")
    
    # We use Python's f-string to inject the column name into the SQL query
    query = f"""
        SELECT {col}, COUNT(*) AS frequency
        FROM raw_jobs
        GROUP BY {col}
        ORDER BY frequency DESC
        LIMIT 5;
    """
    
    # Using display() makes the output look like nice pandas dataframes in Jupyter
    display(con.sql(query).df())

--- Top 5 Value Counts for: categories ---

                                          categories  frequency
0    [{"id":21,"category":"Information Technology"}]      92869
1               [{"id":11,"category":"Engineering"}]      49494
2                       [{"id":15,"category":"F&B"}]      48461
3  [{"id":1,"category":"Accounting / Auditing / T...      44720
4  [{"id":6,"category":"Building and Construction"}]      44374

--- Top 5 Value Counts for: employmentTypes ---

  employmentTypes  frequency
0       Permanent     458139
1       Full Time     393352
2        Contract     139182
3       Part Time      25431
4       Temporary      18241

--- Top 5 Value Counts for: metadata_expiryDate ---

  metadata_expiryDate  frequency
0          2023-07-28       4487
1          2023-07-06       4341
2          2023-07-12       4306
3          2023-07-05       4291
4          2023-07-26       4267

--- Top 5 Value Counts for: metadata_isPostedOnBehalf ---

   metadata_isPostedOnBehalf  frequency
0                      False     986717
1                       True      61868

--- Top 5 Value Counts for: metadata_jobPostId ---

  metadata_jobPostId  frequency
0               None       3988
1   MCF-2023-0768483          1
2   MCF-2023-0768855          1
3   MCF-2023-0768426          1
4   MCF-2023-0768951          1

--- Top 5 Value Counts for: metadata_newPostingDate ---

  metadata_newPostingDate  frequency
0              2023-06-09       4508
1              2023-06-28       4337
2              2023-06-05       4215
3              2023-06-06       4188
4              2023-07-14       4169

--- Top 5 Value Counts for: metadata_originalPostingDate ---

  metadata_originalPostingDate  frequency
0                   2023-07-14       4029
1                   2024-04-03       4020
2                          NaT       3988
3                   2023-10-12       3974
4                   2024-05-14       3938

--- Top 5 Value Counts for: metadata_repostCount ---

   metadata_repostCount  frequency
0                     0    1005855
1                     1      28078
2                     2      14652

--- Top 5 Value Counts for: metadata_totalNumberJobApplication ---

   metadata_totalNumberJobApplication  frequency
0                                   0     660363
1                                   1     246159
2                                   2      23284
3                                   3      16627
4                                   4      12949

--- Top 5 Value Counts for: metadata_totalNumberOfView ---

   metadata_totalNumberOfView  frequency
0                           0     183109
1                           1     127738
2                           2      96349
3                           3      73658
4                           4      57729

--- Top 5 Value Counts for: minimumYearsExperience ---

   minimumYearsExperience  frequency
0                       1     264085
1                       2     219909
2                       3     169787
3                       5     145154
4                       0     118439

--- Top 5 Value Counts for: numberOfVacancies ---

   numberOfVacancies  frequency
0                  1     590242
1                  2     195718
2                  3     111947
3                  5      64760
4                 10      26547

--- Top 5 Value Counts for: occupationId ---

  occupationId  frequency
0         None    1048585

--- Top 5 Value Counts for: positionLevels ---

      positionLevels  frequency
0          Executive     253701
1   Junior Executive     167656
2      Non-executive     131608
3  Fresh/entry level     118661
4       Professional     112208

--- Top 5 Value Counts for: postedCompany_name ---

                  postedCompany_name  frequency
0  THE SUPREME HR ADVISORY PTE. LTD.      61638
1             RECRUITPEDIA PTE. LTD.      50444
2            RECRUIT EXPRESS PTE LTD      33170
3                  ANRADUS PTE. LTD.      25805
4           RECRUIT EXPERT PTE. LTD.      21608

--- Top 5 Value Counts for: salary_maximum ---

   salary_maximum  frequency
0            5000      86521
1            4000      71302
2            3500      71161
3            4500      65420
4            6000      56530

--- Top 5 Value Counts for: salary_minimum ---

   salary_minimum  frequency
0            3000     145381
1            2500      97674
2            4000      70221
3            3500      66359
4            2000      66182

--- Top 5 Value Counts for: salary_type ---

  salary_type  frequency
0     Monthly    1044597
1        None       3988

--- Top 5 Value Counts for: status_id ---

   status_id  frequency
0          0    1048585

--- Top 5 Value Counts for: status_jobStatus ---

  status_jobStatus  frequency
0             Open     902614
1           Closed     119701
2          Re-open      22282
3             None       3988

--- Top 5 Value Counts for: title ---

                title  frequency
0          SUPERVISOR       8331
1          Supervisor       4179
2                None       3988
3   Quantity Surveyor       3076
4  Accounts Executive       2999

--- Top 5 Value Counts for: average_salary ---

   average_salary  frequency
0          4000.0      55954
1          3500.0      38587
2          3000.0      36940
3          4500.0      35556
4          3750.0      34037

In [ ]:
# rename all the column (as per Data Dictionary)
rename_query = """
    CREATE OR REPLACE TABLE renamed_jobs AS 
    SELECT 
        -- SYNTAX: original_column_name AS New_Column_Name
        
        categories AS Category,
        employmentTypes AS Employment_Type,
        positionLevels AS Position_Level,
        postedCompany_name AS Company_Name,
        status_jobStatus AS Job_Status,
        
        metadata_expiryDate AS Expiry_Date,
        metadata_newPostingDate AS New_Post_Date,
        metadata_originalPostingDate AS Orig_Post_Date,
        
        metadata_isPostedOnBehalf AS Posted_On_Behalf,
        metadata_jobPostId AS Job_Post_ID,
        
        metadata_repostCount AS Repost_Date,
        metadata_totalNumberJobApplication AS Total_Applications,
        metadata_totalNumberOfView AS Total_Views,
        minimumYearsExperience AS Min_Yrs_Experience,
        numberOfVacancies AS Vacancies,
        salary_minimum AS Salary_Min,
        salary_maximum AS Salary_Max
        
        -- drop "salary_type" at the same time, as it has only 1 unique value 'monthly'
        -- drop "status_id", as it has only 1 unique value '0'
        
    FROM raw_jobs;
"""

# Execute the query
con.sql(rename_query)

# View the result to verify the column headers have changed
con.sql("SELECT * FROM renamed_jobs LIMIT 5").df()

In [25]:
# cleaning query
transform_query = """
    COPY (
        SELECT 
            -- 1. Explode JSON
            json_extract_string(categories, '$[0].category') AS Category,
            
            -- 2. Rename standard columns
            employmentTypes AS Employment_Type,
            positionLevels AS Position_Level,
            postedCompany_name AS Company_Name,
            status_jobStatus AS Job_Status,
            
            -- 3. Date formats
            CAST(metadata_expiryDate AS DATE) AS Expiry_Date,
            CAST(metadata_newPostingDate AS DATE) AS New_Post_Date,
            CAST(metadata_originalPostingDate AS DATE) AS Orig_Post_Date,
            
            -- 4. Booleans
            CAST(metadata_isPostedOnBehalf AS BOOLEAN) AS Posted_On_Behalf,
            
            -- 5. IDs
            metadata_jobPostId AS Job_Post_ID,
            
            -- 6. Numerics
            CAST(metadata_repostCount AS INTEGER) AS Repost_Count, 
            CAST(metadata_totalNumberJobApplication AS INTEGER) AS Total_Applications,
            CAST(metadata_totalNumberOfView AS INTEGER) AS Total_Views,
            CAST(minimumYearsExperience AS INTEGER) AS Min_Yrs_Experience,
            CAST(numberOfVacancies AS INTEGER) AS Vacancies,
            CAST(salary_minimum AS INTEGER) AS Salary_Min,
            CAST(salary_maximum AS INTEGER) AS Salary_Max
            
        FROM raw_jobs
        
        -- Filter out bad rows
        WHERE metadata_jobPostId IS NOT NULL 
          AND metadata_jobPostId != ''
          
    ) TO '../data/SGJobData_Cleaned_SQL.csv' (HEADER, DELIMITER ',');
"""

print("Executing SQL Transformation...")

con.sql(transform_query)
print("Success! Cleaned data saved to 'data/SGJobData_Cleaned_SQL.csv'")

Executing SQL Transformation...
Success! Cleaned data saved to 'data/SGJobData_Cleaned_SQL.csv'